version: '3.8'

services:
  fastapi:
    build:
      context: ./src/backend/api
      dockerfile: Dockerfile
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend/api:/app
       - /app/.venv
    environment:
      - VITE_API_URL=http://fastapi:8000
      - PYTHONUNBUFFERED=1
      - ROLLUP_DISABLE_NATIVE=1
    restart: unless-stopped
    networks:
      - app-network


# services:
#   backend:
#     build:
#       context: ./src/backend/api
#     container_name: backend
#     env_file:
#       - .env
#     environment:
#       - VITE_API_URL=http://backend:5000
#       - NEO4J_URI=bolt://${NEO4J_IP}:7687
#       - ROLLUP_DISABLE_NATIVE=1
#     ports:
#       - "5000:5000"
#     volumes:
#       - ./src/backend/api:/app
#     networks:
#       - app-network
      
  frontend:
    build:
      context: ./src/vulnerability-frontend
    container_name: frontend
    environment:
      - VITE_API_URL=http://backend:8000 # Should we change this por for 8000?
      - ROLLUP_DISABLE_NATIVE=1
    ports:
      - "5173:5173" 
    volumes:
      - ./src/vulnerability-frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - fastapi

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
