services:
  backend:
    build:
      context: ./src/backend
    container_name: backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://backend:5000
      - NEO4J_URI=bolt://${NEO4J_IP}:7687
      - ROLLUP_DISABLE_NATIVE=1
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/app
    networks:
      - app-network
      
  frontend:
    build:
      context: ./src/vulnerability-frontend
    container_name: frontend
    environment:
      - VITE_API_URL=http://backend:5000
      - ROLLUP_DISABLE_NATIVE=1
    ports:
      - "5173:5173" 
    volumes:
      - ./src/vulnerability-frontend:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
